apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: Sathwik-Anumala
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jenkinsx-http-gradle
    - name: jenkinsx-http-node
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
